add signature verification (we recommend hosty reinstallation)

diff --git a/hosty b/hosty
--- a/hosty
+++ b/hosty
@@ -1,2 +1,34 @@
 #!/bin/bash
-bash <(curl -s https://raw.githubusercontent.com/astrolince/hosty/master/hosty.sh) $*
+
+# Creating tmp files
+astrokeys=$(mktemp)
+hosty=$(mktemp)
+signature=$(mktemp)
+
+# Download function
+downloadFiles() {
+    curl -L -s -S -o $1 $2
+
+    if [ $? != 0 ]; then
+        echo "Error downloading $2"
+        exit 1
+    fi
+}
+
+# Download files
+downloadFiles "$astrokeys" https://keybase.io/astrolince/pgp_keys.asc
+downloadFiles "$hosty" https://raw.githubusercontent.com/astrolince/hosty/master/hosty.sh
+downloadFiles "$signature" https://raw.githubusercontent.com/astrolince/hosty/master/hosty.sh.sig
+
+# Verify signature
+gpg --dearmor "$astrokeys"
+gpg --no-default-keyring --keyring "$astrokeys.gpg" --verify "$signature" "$hosty" &>/dev/null
+
+# If there is a problem, kill program
+if [ $? -eq 0 ]
+then
+	bash <(cat $hosty) $*
+else
+    echo "There is a problem with the signature, probably hosty repository was compromised, no changes were made to your system."
+    exit 1
+fi
